### ISSUE TITLE
TypeError: Cannot read property 'speedIndex' of undefined

### ISSUE THREAD

**Issue by rickydazla** [springernature/webpagetest-mapper#20]
I've had this tool running for some time, it's sweeet! But, I just ran into this issue that appears at the mapping stage and I'm not sure what to do with it... Help appreciated.

```
2016-10-07 15:00:56 INFO webpagetest-mapper: mapping result 161007_2R_315J [Wholesale]
TypeError: Cannot read property 'speedIndex' of undefined
    at getSimpleValue (/usr/local/lib/node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:482:44)
    at getValue (/usr/local/lib/node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:423:12)
    at filterResults (/usr/local/lib/node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:415:12)
    at Array.filter (native)

    at mapChart (/usr/local/lib/node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:379:35)
    at Array.map (native)
    at mapResults (/usr/local/lib/node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:159:24)
    at Object.map (/usr/local/lib/node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:129:19)
    at map (/usr/local/lib/node_modules/webpagetest-mapper/src/index.js:169:32)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Fatal error, exiting.
```

**Comment by philbooth** [comment]
@rickydazla, can you try this again?

When you first opened the issue, I reproduced it using your `161007_2R_315J` result and made a note to come back and fix it. However, I tried again just now and it worked fine. Not sure if there was a server-side problem that might have been affecting the results somehow?

**Comment by philbooth** [comment]
Log output from `wptmap -i 161007_2R_315J`:

```
2016-10-15 16:10:16 INFO webpagetest-mapper: fetching SpeedIndex result 161007_2R_315J [undefined]
2016-10-15 16:10:16 INFO webpagetest-mapper: fetching TTFB result 161007_2R_315J [undefined]
2016-10-15 16:10:16 INFO webpagetest-mapper: fetching render result 161007_2R_315J [undefined]
2016-10-15 16:10:16 INFO webpagetest-mapper: fetching loadTime result 161007_2R_315J [undefined]
2016-10-15 16:10:18 INFO webpagetest-mapper: finished fetching render result 161007_2R_315J [undefined]
2016-10-15 16:10:18 INFO webpagetest-mapper: finished fetching SpeedIndex result 161007_2R_315J [undefined]
2016-10-15 16:10:18 INFO webpagetest-mapper: finished fetching loadTime result 161007_2R_315J [undefined]
2016-10-15 16:10:18 INFO webpagetest-mapper: finished fetching TTFB result 161007_2R_315J [undefined]
2016-10-15 16:10:18 INFO webpagetest-mapper: mapping result 161007_2R_315J [20161007-142314-08-wholesale]
```

**Comment by rickydazla** [comment]
Oh yeah, good. Great! Thanks
