### ISSUE TITLE
Unable to parse results from WPT ids

### ISSUE THREAD

**Issue by desmondtam** [springernature/webpagetest-mapper#23]
computer:~ user$ wptmap -i 170626_Y8_308ce7649ececcd89de9376d8be95b3c

2017-07-20 10:06:46 INFO webpagetest-mapper: fetching SpeedIndex result 170626_Y8_308ce7649ececcd89de9376d8be95b3c [undefined]
2017-07-20 10:06:46 INFO webpagetest-mapper: fetching TTFB result 170626_Y8_308ce7649ececcd89de9376d8be95b3c [undefined]
2017-07-20 10:06:46 INFO webpagetest-mapper: fetching render result 170626_Y8_308ce7649ececcd89de9376d8be95b3c [undefined]
2017-07-20 10:06:46 INFO webpagetest-mapper: fetching loadTime result 170626_Y8_308ce7649ececcd89de9376d8be95b3c [undefined]
2017-07-20 10:06:47 INFO webpagetest-mapper: finished fetching render result 170626_Y8_308ce7649ececcd89de9376d8be95b3c [undefined]
2017-07-20 10:06:47 INFO webpagetest-mapper: finished fetching SpeedIndex result 170626_Y8_308ce7649ececcd89de9376d8be95b3c [undefined]
2017-07-20 10:06:47 INFO webpagetest-mapper: finished fetching TTFB result 170626_Y8_308ce7649ececcd89de9376d8be95b3c [undefined]
2017-07-20 10:06:47 INFO webpagetest-mapper: finished fetching loadTime result 170626_Y8_308ce7649ececcd89de9376d8be95b3c [undefined]
2017-07-20 10:06:47 INFO webpagetest-mapper: mapping result 170626_Y8_308ce7649ececcd89de9376d8be95b3c [Desk_170625a]
2017-07-20 10:06:47 ERROR webpagetest-mapper: failed to map result 170626_Y8_308ce7649ececcd89de9376d8be95b3c [Desk_170625a]; Cannot read property 'run' of undefined
TypeError: Cannot read property 'speedIndex' of undefined
    at getSimpleValue (/usr/local/lib/node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:482:44)
    at getValue (/usr/local/lib/node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:423:12)
    at filterResults (/usr/local/lib/node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:415:12)
    at Array.filter (native)
    at mapChart (/usr/local/lib/node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:379:35)
    at Array.map (native)
    at mapResults (/usr/local/lib/node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:159:24)
    at Object.map (/usr/local/lib/node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:129:19)
    at map (/usr/local/lib/node_modules/webpagetest-mapper/src/index.js:169:32)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Fatal error, exiting.

**Comment by mnovinger** [comment]
I see the same when trying to map test results against a private instance

**Comment by rcherny** [comment]
@mnovinger I've seen this when doing `firstViewOnly` on the tests, and then there's no `repeatView` for it to be finding runs against.
